"""Procedures for visualizing 2D and 3D TSPs and tours.

`visualize_tsp_pil` and `visualize_mst_pil` use the Python Imaging Library (PIL) backend, saving
image files with visualizations of 2D TSPs and MSTs (MSTs generated by `tsp.core.pyramid_old.mst`).

`visualize_3d` uses PIL and OpenCV to generate a movie visualizing 3D TSPs and tours using 3D
motion.

`visualize_tsp_plt` and `visualize_mst_plt` are similar to their associated `_pil` procedures, but
use the MatPlotLib backend. Can also be used to generate image files using the associated
MatPlotLib directives, but are also great for inlining in Jupyter notebooks, etc.
"""


from math import sin, cos, radians
from typing import Iterable, Tuple, Union
from numbers import Number
from numpy.typing import NDArray
import numpy as np
from PIL import Image, ImageDraw
import matplotlib.pyplot as plt
from matplotlib.axes import SubplotBase

from tsp.core.tsp import TSP


def _draw_edges_pil(im: Image, tsp: TSP, edges: Iterable[Tuple[int, int]]):
    draw = ImageDraw.Draw(im)
    for e1, e2 in edges:
        e1 = tuple(tsp.cities[e1] * 2)
        e2 = tuple(tsp.cities[e2] * 2)
        draw.line([e1, e2], fill='blue', width=6)


def _draw_cities_pil(im: Image, tsp: TSP):
    draw = ImageDraw.Draw(im)
    for x, y in tsp.cities:
        draw.ellipse([(x*2 - 8, y*2 - 8), (x*2 + 8, y*2 + 8)], fill='red', outline='red')


def _draw_tour_pil(im: Image, tsp: TSP, tour: Iterable[Union[int, NDArray]]):
    draw = ImageDraw.Draw(im)
    s = list(tour)
    if isinstance(s[0], Number):
        draw.line([(x*2, y*2) for x, y in tsp.tour_segments(s)], fill='blue', width=6)
    else:
        draw.line([(x*2, y*2) for x, y in s], fill='blue', width=6)


def visualize_tsp_pil(tsp: TSP, tour: Iterable[Union[int, NDArray]], path: str):
    """Generate and save visualization of a TSP using PIL backend.

    Args:
        tsp (TSP): the problem
        tour (Iterable[Union[int, NDArray]]): tour either as indices of vertices or as segments
        path (str): path to save
    """
    im = Image.new('RGB', (tsp.w * 2, tsp.h * 2), color = 'white')
    if len(tour):
        _draw_tour_pil(im, tsp, tour)
    _draw_cities_pil(im, tsp)
    im.thumbnail((tsp.w, tsp.h))
    im.save(path)


def visualize_mst_pil(tsp: TSP, mst: Iterable[Tuple[float, Tuple[int, int]]], path: str):
    """Generate and save visualization of an MST using PIL backend.

    Args:
        tsp (TSP): the problem
        mst (Iterable[Tuple[float, Typle[int, int]]]): edges in MST
        path (str): path to save
    """
    im = Image.new('RGB', (tsp.w * 2, tsp.h * 2), color = 'white')
    _draw_edges_pil(im, tsp, list(zip(*mst))[1])
    _draw_cities_pil(im, tsp)
    im.thumbnail((tsp.w, tsp.h))
    im.save(path)


def _draw_edges_plt(ax: SubplotBase, tsp: TSP, edges: Iterable[Tuple[int, int]]):
    for e1, e2 in edges:
        e1 = np.copy(tsp.cities[e1])
        e2 = np.copy(tsp.cities[e2])
        e1[1] = tsp.h - e1[1]
        e2[1] = tsp.h - e2[1]
        ax.plot(*zip(e1, e2), 'b-')


def _draw_cities_plt(ax: SubplotBase, tsp: TSP):
    cities = np.array(list(zip(*tsp.cities)))
    cities[1] = tsp.h - cities[1]
    ax.plot(*cities, 'ro')


def _draw_tour_plt(ax: SubplotBase, tsp: TSP, tour: Iterable[Union[int, NDArray]]):
    s = list(tour)
    if isinstance(s[0], Number):
        edges = np.array(list(zip(*list(tsp.tour_segments(s)))))
    else:
        edges = np.array(list(zip(*s)))
    edges[1] = tsp.h - edges[1]
    ax.plot(*edges, 'b-')


def _init_plot(ax: SubplotBase, tsp: TSP):
    if ax is None:
        ax = plt.subplot(111)

    ax.set_xlim((0, tsp.w))
    ax.set_ylim((0, tsp.h))
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_aspect('equal', 'box')

    return ax


def visualize_tsp_plt(tsp: TSP, tour: Iterable[Union[int, NDArray]], ax: SubplotBase = None):
    """Generate visualization of a TSP using MatPlotLib backend.

    Args:
        tsp (TSP): the problem
        tour (Iterable[Union[int, NDArray]]): tour either as indices of vertices or as segments
        ax (SubplotBase): Matplotlib axes to plot on. Defaults to None.
    """
    ax = _init_plot(ax, tsp)

    if len(tour):
        _draw_tour_plt(ax, tsp, tour)
    _draw_cities_plt(ax, tsp)


def visualize_mst_plt(tsp: TSP, mst: Iterable[Tuple[float, Tuple[int, int]]], ax: SubplotBase = None):
    """Generate visualization of an MST using MatPlotLib backend.

    Args:
        tsp (TSP): the problem
        mst (Iterable[Tuple[float, Typle[int, int]]]): edges in MST
        ax (SubplotBase): Matplotlib axes to plot on. Defaults to None.
    """
    ax = _init_plot(ax, tsp)

    _draw_edges_plt(ax, tsp, list(zip(*mst))[1])
    _draw_cities_plt(ax, tsp)
