"""Procedures for visualizing 2D and 3D TSPs and tours.

`visualize_tsp_pil` and `visualize_mst_pil` use the Python Imaging Library (PIL) backend, saving
image files with visualizations of 2D TSPs and MSTs (MSTs generated by `tsp.core.pyramid_old.mst`).

`visualize_3d` uses PIL and OpenCV to generate a movie visualizing 3D TSPs and tours using 3D
motion.

`visualize_tsp_plt` and `visualize_mst_plt` are similar to their associated `_pil` procedures, but
use the MatPlotLib backend. Can also be used to generate image files using the associated
MatPlotLib directives, but are also great for inlining in Jupyter notebooks, etc.
"""


from math import sin, cos, radians
from typing import Iterable, Union
from numpy.typing import NDArray
import numpy as np
from cv2 import cv2

from tsp.core.tsp import N_TSP, TSP
from tsp.core.viz import visualize_mst_pil


def visualize_3d(tsp: N_TSP, tour: Iterable[Union[int, NDArray]], path: str, step: int = 1, time: int = 12):
    """Generate and save visualization of 3D motion of a 3D TSP as an mp4.

    Args:
        tsp (N_TSP): the problem
        tour (Iterable[Union[int, NDArray]]): tour either as indices of vertices or as segments
        path (str): path to save
        step (int, optional): Degrees to rotate per frame. Defaults to 1.
        time (int, optional): Duration of generated video. Defaults to 12.
    """
    assert tsp.dimensions == 3
    min_x, min_y, max_x, max_y = float('inf'), float('inf'), float('-inf'), float('-inf')
    for alpha in range(0, 360, step):
        for x, y, z in tsp.cities:
            x_ = x*cos(radians(alpha)) + z*sin(radians(alpha))
            y_ = y
            min_x = min(min_x, x_)
            min_y = min(min_y, y_)
            max_x = max(max_x, x_)
            max_y = max(max_y, y_)
    min_x -= 10  # padding
    min_y -= 10
    max_x -= min_x - 10  # padding on max side
    max_y -= min_y - 10
    min_x, min_y, max_x, max_y = int(min_x), int(min_y), int(max_x), int(max_y)

    video = cv2.VideoWriter(path, cv2.VideoWriter_fourcc(*'mp4v'), int(round((360 / step) / time)), (max_x, max_y))
    for alpha in range(0, 360, step):
        new_coords = []
        for x, y, z in tsp.cities:
            new_coords.append((
                x*cos(radians(alpha)) + z*sin(radians(alpha)),
                y
            ))
        new_coords = np.array(new_coords, dtype=np.int)
        new_coords -= np.array([min_x, min_y])

        new_t = TSP.from_cities(new_coords, w=max_x, h=max_y)
        visualize_mst_pil(new_t, tour, '/tmp/viz.png')
        video.write(cv2.imread('/tmp/viz.png'))
    video.release()
